apply plugin: 'com.android.application'
android {
    compileSdkVersion 30
    defaultConfig {
        applicationId "com.mingyue0094.networkcamera"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode 3
        versionName "3.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
